fix av1

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -189,13 +189,14 @@ jobs:
                 --extra-ldflags="-L${{ env.ZIMG_INSTALL }}/lib -L${{ env.DAV1D_INSTALL }}/lib -L${{ env.OPENSSL_INSTALL }}/lib -L${{ env.WEBP_INSTALL }}/lib -L${{ env.ZLIB_INSTALL }}/lib -L${{ env.JXL_INSTALL }}/lib -L${{ env.BROTLI_INSTALL }}/lib -L${{ env.HWY_INSTALL }}/lib -static" \
                 --extra-libs="-lssl -lcrypto -lwebp -lsharpyuv -lz -ljxl -ljxl_threads -lhwy -lbrotlienc -lbrotlidec -lbrotlicommon -lpthread -lm -ldl -lstdc++" \
                 --enable-openssl \
-                --disable-x86asm --disable-inline-asm \
+                --disable-x86asm --disable-inline-asm --disable-hwaccels \
                 --disable-everything --enable-ffmpeg --enable-version3 --enable-libwebp --enable-libjxl --enable-zlib \
                 --enable-protocol=file,http,https,tls,tcp,tls_openssl,dns,httpproxy,crypto \
                 --enable-demuxer=mov,matroska,avi,flv,mpegts,mpeg,mpegps,asf,ogg,rm,mxf,mpegvideo,image2,gif,heif,avif,jxl,ico,webp,psd,dds,j2k,jp2,pnm,sgi \
-                --enable-decoder=h264,hevc,vp9,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv,flv1,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
+                --enable-decoder=h264,hevc,vp9,av1,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv,flv1,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
                 --enable-parser=h264,hevc,mpeg4video,mpegvideo,av1,h263,mpegaudio,ac3,mjpeg,png,webp,gif \
-                --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static" \
+                --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static"
+              CFG_MAK=config.mak; [ -f ffbuild/config.mak ] && CFG_MAK=ffbuild/config.mak; grep -q '^CONFIG_AV1_DECODER=yes' "$CFG_MAK" || { echo "ERROR: AV1 decoder not enabled ($CFG_MAK)"; exit 1; }
               ;;
             linux-arm64)
               export PKG_CONFIG_LIBDIR="${{ env.ZIMG_INSTALL }}/lib/pkgconfig:${{ env.DAV1D_INSTALL }}/lib/pkgconfig:${{ env.OPENSSL_INSTALL }}/lib/pkgconfig:${{ env.WEBP_INSTALL }}/lib/pkgconfig:${{ env.ZLIB_INSTALL }}/lib/pkgconfig:${{ env.BROTLI_INSTALL }}/lib/pkgconfig:${{ env.JXL_INSTALL }}/lib/pkgconfig"
@@ -223,13 +224,14 @@ jobs:
                 --extra-ldflags="-L${{ env.ZIMG_INSTALL }}/lib -L${{ env.DAV1D_INSTALL }}/lib -L${{ env.OPENSSL_INSTALL }}/lib -L${{ env.WEBP_INSTALL }}/lib -L${{ env.ZLIB_INSTALL }}/lib -L${{ env.JXL_INSTALL }}/lib -L${{ env.BROTLI_INSTALL }}/lib -L${{ env.HWY_INSTALL }}/lib -static" \
                 --extra-libs="-lssl -lcrypto -lwebp -lsharpyuv -lz -ljxl -ljxl_threads -lhwy -lbrotlienc -lbrotlidec -lbrotlicommon -lpthread -lm -ldl -lstdc++" \
                 --enable-openssl \
-                --disable-x86asm --disable-inline-asm \
+                --disable-x86asm --disable-inline-asm --disable-hwaccels \
                 --disable-everything --enable-ffmpeg --enable-version3 --enable-libwebp --enable-libjxl --enable-zlib \
                 --enable-protocol=file,http,https,tls,tcp,tls_openssl,dns,httpproxy,crypto \
                 --enable-demuxer=mov,matroska,avi,flv,mpegts,mpeg,mpegps,asf,ogg,rm,mxf,mpegvideo,image2,gif,heif,avif,jxl,ico,webp,psd,dds,j2k,jp2,pnm,sgi \
-                --enable-decoder=h264,hevc,vp9,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv,flv1,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
+                --enable-decoder=h264,hevc,vp9,av1,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv,flv1,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
                 --enable-parser=h264,hevc,mpeg4video,mpegvideo,av1,h263,mpegaudio,ac3,mjpeg,png,webp,gif \
-                --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static" \
+                --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static"
+              CFG_MAK=config.mak; [ -f ffbuild/config.mak ] && CFG_MAK=ffbuild/config.mak; grep -q '^CONFIG_AV1_DECODER=yes' "$CFG_MAK" || { echo "ERROR: AV1 decoder not enabled ($CFG_MAK)"; exit 1; }
               ;;
             windows-x86_64)
               # Set PKG_CONFIG_PATH to our custom installs
@@ -261,12 +263,14 @@ jobs:
                 --extra-cflags="-I${{ env.ZIMG_INSTALL }}/include -I${{ env.DAV1D_INSTALL }}/include -I${{ env.WEBP_INSTALL }}/include -I${{ env.ZLIB_INSTALL }}/include -I${{ env.JXL_INSTALL }}/include -I${{ env.BROTLI_INSTALL }}/include -I${{ env.HWY_INSTALL }}/include" \
                 --extra-ldflags="-L${{ env.ZIMG_INSTALL }}/lib -L${{ env.DAV1D_INSTALL }}/lib -L${{ env.WEBP_INSTALL }}/lib -L${{ env.ZLIB_INSTALL }}/lib -L${{ env.JXL_INSTALL }}/lib -L${{ env.BROTLI_INSTALL }}/lib -L${{ env.HWY_INSTALL }}/lib -static" \
                 --extra-libs="-lwebp -lsharpyuv -lz -ljxl -ljxl_threads -lhwy -lbrotlienc -lbrotlidec -lbrotlicommon -lstdc++ -lpthread" \
+                --disable-hwaccels \
                 --disable-everything --enable-ffmpeg --enable-version3 --enable-libwebp --enable-libjxl --enable-zlib \
                 --enable-protocol=file,http,https,tcp,tls \
                 --enable-demuxer=mov,matroska,avi,flv,mpegts,mpeg,mpegps,asf,ogg,rm,mxf,mpegvideo,image2,gif,heif,avif,jxl,ico,webp,psd,dds,j2k,jp2,pnm,sgi \
-                --enable-decoder=h264,hevc,vp9,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv1,flv,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
+                --enable-decoder=h264,hevc,vp9,av1,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv1,flv,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
                 --enable-parser=h264,hevc,mpeg4video,mpegvideo,av1,h263,mpegaudio,ac3,mjpeg,png,webp,gif \
-                --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static" \
+                --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static"
+              CFG_MAK=config.mak; [ -f ffbuild/config.mak ] && CFG_MAK=ffbuild/config.mak; grep -q '^CONFIG_AV1_DECODER=yes' "$CFG_MAK" || { echo "ERROR: AV1 decoder not enabled ($CFG_MAK)"; exit 1; }
               ;;
           esac
 
@@ -379,12 +383,14 @@ jobs:
             --arch=${{ matrix.arch }} --cc="clang -arch ${{ matrix.arch }}" --cxx="clang++ -arch ${{ matrix.arch }}" --target-os=darwin \
             --extra-cflags="-I${{ env.INSTALL_DIR }}/include" --extra-ldflags="-L${{ env.INSTALL_DIR }}/lib" \
             --extra-libs="-lwebp -lsharpyuv -lz -ljxl -ljxl_threads -lhwy -lbrotlienc -lbrotlidec -lbrotlicommon -lpthread -lm -lstdc++" \
+            --disable-hwaccels \
             --disable-everything --enable-ffmpeg --enable-version3 --enable-libwebp --enable-libjxl --enable-zlib \
             --enable-protocol=file,http,https,tcp,tls \
             --enable-demuxer=mov,matroska,avi,flv,mpegts,mpeg,mpegps,asf,ogg,rm,mxf,mpegvideo,image2,gif,heif,avif,jxl,ico,webp,psd,dds,j2k,jp2,pnm,sgi \
-            --enable-decoder=h264,hevc,vp9,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv,flv1,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
+            --enable-decoder=h264,hevc,vp9,av1,libdav1d,mpeg1video,mpeg2video,mpeg4,msmpeg4v3,wmv3,rv10,rv20,rv30,rv40,h263,h263p,h263i,mp3,mp2,ac3,aac,mpegvideo,flv,flv1,vp6,vp6f,vp6a,theora,dnxhd,prores,mjpeg,png,webp,libwebp,gif,bmp,tiff,ico,targa,pcx,xbm,alias_pix,sunrast,xwd,jxl,libjxl,psd,dds,jpeg2000,pam,pbm,pgm,ppm,sgi \
             --enable-parser=h264,hevc,mpeg4video,mpegvideo,av1,h263,mpegaudio,ac3,mjpeg,png,webp,gif \
             --enable-bsf=hevc_metadata,av1_metadata,vp9_metadata --enable-libzimg --enable-libdav1d --enable-filter=scale,format,zscale,tonemap --enable-encoder=mjpeg,png,libwebp,webp --enable-muxer=image2 --enable-avcodec --enable-avformat --enable-avutil --enable-swscale --disable-doc --disable-debug --enable-network --disable-ffplay --disable-ffprobe --pkg-config=pkg-config --pkg-config-flags="--static"
+          CFG_MAK=config.mak; [ -f ffbuild/config.mak ] && CFG_MAK=ffbuild/config.mak; grep -q '^CONFIG_AV1_DECODER=yes' "$CFG_MAK" || { echo "ERROR: AV1 decoder not enabled ($CFG_MAK)"; exit 1; }
           make -j$(sysctl -n hw.ncpu)
           cp ffmpeg ../ffmpeg-macos-${{ matrix.arch }}
 
@@ -393,3 +399,4 @@ jobs:
         with:
           name: ffmpeg-macos-${{ matrix.arch }}
           path: ffmpeg-macos-*
+
